//! `flutter-cli init <shell>` — emit a shell function that intercepts
//! the `flutter` command so `flutter run`/`test`/`build`/`devices` route
//! through `flutter-cli` (with the TUI) and everything else falls
//! through to the real `flutter` binary.
//!
//! Modeled after the starship / zoxide / direnv init pattern: the
//! user adds a single `eval "$(fl init <shell>)"` line to their rc
//! file. No copy-pasting, no manual file edits — and uninstalling is
//! as simple as removing that one line.

use crate::cli::ShellKind;

/// Subcommands we intercept. Anything else (pub, doctor, clean,
/// analyze, channel, upgrade, …) passes through to the real
/// `flutter` binary so IDEs / scripts that exec it directly aren't
/// surprised.
const INTERCEPTED: &[&str] = &["run", "test", "build", "devices"];

pub async fn run(shell: ShellKind) -> anyhow::Result<()> {
    let script = match shell {
        ShellKind::Zsh | ShellKind::Bash => render_posix(),
        ShellKind::Fish => render_fish(),
    };
    print!("{script}");
    Ok(())
}

/// POSIX-shell (bash + zsh) shim. We define a function named
/// `flutter` that dispatches the first positional argument: matched
/// subcommands go to `fl`, anything else (and the bare `flutter` call
/// with no args) goes to the real binary via `command flutter`, which
/// bypasses the function we just defined so there's no infinite loop.
fn render_posix() -> String {
    let cases = INTERCEPTED
        .iter()
        .map(|cmd| format!("    {cmd}) shift; command flutter-cli {cmd} \"$@\" ;;"))
        .collect::<Vec<_>>()
        .join("\n");
    // `unalias` first because aliases are resolved BEFORE functions in
    // zsh/bash — without this, a stray `alias flutter=...` from
    // oh-my-zsh's flutter plugin (or fvm, asdf, the user's own dotfiles)
    // shadows our shim and `flutter run` falls through to the real
    // binary silently. The `2>/dev/null` swallows the "no such alias"
    // error when there isn't one to remove.
    format!(
        r#"# flutter-cli shim — generated by `flutter-cli init`. Drop in
# your rc file via:
#   eval "$(flutter-cli init zsh)"     # or `bash`
# Place this AFTER any other tool that defines `flutter` (fvm, asdf,
# oh-my-zsh's flutter plugin, …) so our function wins. To uninstall,
# remove the eval line and start a new shell.
unalias flutter 2>/dev/null
flutter() {{
  case "$1" in
{cases}
    *) command flutter "$@" ;;
  esac
}}
"#
    )
}

/// Fish shim. Syntax differs enough from POSIX that we render a
/// separate function. `command flutter $argv` bypasses fish's own
/// function lookup, same trick as the POSIX version.
fn render_fish() -> String {
    let cases = INTERCEPTED
        .iter()
        .map(|cmd| format!("    case {cmd}\n        command flutter-cli {cmd} $argv[2..]"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"# flutter-cli shim — generated by `flutter-cli init fish`.
# Drop this in ~/.config/fish/config.fish via:
#   flutter-cli init fish | source
function flutter
    switch $argv[1]
{cases}
    case '*'
        command flutter $argv
    end
end
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn posix_shim_intercepts_known_subcommands_and_falls_through_for_others() {
        let s = render_posix();
        // Each intercepted subcommand should map to `fl <cmd>`.
        for cmd in INTERCEPTED {
            assert!(
                s.contains(&format!("command flutter-cli {cmd}")),
                "missing interception for `{cmd}`:\n{s}"
            );
        }
        // The catch-all has to go through `command flutter` —
        // otherwise we'd recurse into our own shim infinitely.
        assert!(
            s.contains(r#"*) command flutter "$@""#),
            "missing fall-through:\n{s}"
        );
    }

    #[test]
    fn fish_shim_uses_switch_and_command_flutter() {
        let s = render_fish();
        assert!(s.contains("function flutter"));
        assert!(s.contains("command flutter $argv"));
        for cmd in INTERCEPTED {
            assert!(
                s.contains(&format!("command flutter-cli {cmd} $argv[2..]")),
                "missing fish interception for `{cmd}`:\n{s}"
            );
        }
    }
}
